In [72]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


In [73]:
# loading the data from the csv file to apandas dataframe
movies_data = pd.read_csv('/content/Movies.csv')

In [74]:
# printing the first 5 rows of the dataframe
movies_data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...     162   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...     169   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...     148   
3  Following the death of District Attorney Harve...  107.376788  ...     165   
4  John Carter is a war-weary, former military ca...   43.926995  ...     132   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [75]:
# number of rows and columns in the data frame

movies_data.shape

(96, 24)

In [76]:
# selecting the relevant features for recommendation

selected_features = ['genres','keywords','tagline','cast','director']
print(selected_features)

['genres', 'keywords', 'tagline', 'cast', 'director']


In [77]:
# replacing the null valuess with null string

for feature in selected_features:
  movies_data[feature] = movies_data[feature].fillna('')

In [78]:
# combining all the 5 selected features

combined_features = movies_data['genres']+' '+movies_data['keywords']+' '+movies_data['tagline']+' '+movies_data['cast']+' '+movies_data['director']

In [79]:
print(combined_features)

0     Action Adventure Fantasy Science Fiction cultu...
1     Adventure Fantasy Action ocean drug abuse exot...
2     Action Adventure Crime spy based on novel secr...
3     Action Crime Drama Thriller dc comics crime fi...
4     Action Adventure Science Fiction based on nove...
                            ...                        
91    Fantasy Adventure Animation Family flying blac...
92    Action Thriller Science Fiction saving the wor...
93    Action Science Fiction Adventure marvel comic ...
94    Adventure Drama Science Fiction saving the wor...
95    Action Thriller Science Fiction Mystery Advent...
Length: 96, dtype: object


In [80]:
# converting the text data to feature vectors

vectorizer = TfidfVectorizer()

In [81]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [82]:
print(feature_vectors)

  (0, 186)	0.19286328104479727
  (0, 576)	0.13858996237090185
  (0, 977)	0.20611012668105544
  (0, 772)	0.19286328104479727
  (0, 668)	0.2247805069804668
  (0, 1103)	0.20611012668105544
  (0, 1249)	0.2247805069804668
  (0, 1061)	0.2247805069804668
  (0, 999)	0.1825882293052377
  (0, 1304)	0.1825882293052377
  (0, 1286)	0.20611012668105544
  (0, 1001)	0.1462822723350908
  (0, 870)	0.2247805069804668
  (0, 843)	0.12623725790829557
  (0, 1283)	0.13517752565154037
  (0, 1152)	0.0856995351226418
  (0, 375)	0.2247805069804668
  (0, 1078)	0.2247805069804668
  (0, 242)	0.20611012668105544
  (0, 1233)	0.1741929007453859
  (0, 1087)	0.33418950317441976
  (0, 442)	0.1741929007453859
  (0, 234)	0.2247805069804668
  (0, 270)	0.2247805069804668
  (0, 411)	0.08458991941645946
  :	:
  (95, 713)	0.21007727366156853
  (95, 809)	0.19262815120778817
  (95, 333)	0.19262815120778817
  (95, 686)	0.19262815120778817
  (95, 472)	0.19262815120778817
  (95, 611)	0.18024780180265673
  (95, 1295)	0.162798679348876

In [83]:
# getting the similarity scores using cosine similarity

similarity = cosine_similarity(feature_vectors)

In [84]:
print(similarity)

[[1.         0.07833265 0.02986133 ... 0.22128066 0.03566898 0.06348774]
 [0.07833265 1.         0.03247943 ... 0.00880112 0.03309463 0.09466697]
 [0.02986133 0.03247943 1.         ... 0.00748714 0.01195948 0.03232607]
 ...
 [0.22128066 0.00880112 0.00748714 ... 1.         0.01457759 0.02018659]
 [0.03566898 0.03309463 0.01195948 ... 0.01457759 1.         0.07422476]
 [0.06348774 0.09466697 0.03232607 ... 0.02018659 0.07422476 1.        ]]


In [85]:
print(similarity.shape)

(96, 96)


In [86]:
# getting the movie name from the user

movie_name = input(' Enter your favourite movie name : ')

 Enter your favourite movie name : Iron Man 3


In [87]:
# creating a list with all the movie names given in the dataset

list_of_all_titles = movies_data['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lantern', 'Toy Story 3

In [88]:
# finding the close match for the movie name given by the user

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
print(find_close_match)

['Iron Man 3', 'Iron Man 2', 'Iron Man']


In [89]:
close_match = find_close_match[0]
print(close_match)

Iron Man 3


In [90]:
# finding the index of the movie with title

index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]
print(index_of_the_movie)

31


In [91]:
# getting a list of similar movies

similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.01913394232648638), (1, 0.06663144744190379), (2, 0.04906565588283801), (3, 0.07227296785546955), (4, 0.08448870404946178), (5, 0.019939253323283977), (6, 0.07012483412518958), (7, 0.027295469470052014), (8, 0.03069166073852641), (9, 0.04283488994811792), (10, 0.022307171045349725), (11, 0.0023306585893042193), (12, 0.0787342824025054), (13, 0.16125614660092263), (14, 0.07432401233409537), (15, 0.14449469925198977), (16, 0.02629923428880274), (17, 0.0723431156734935), (18, 0.04917194123364781), (19, 0.017354892850379323), (20, 0.01962030992470201), (21, 0.002310113289926264), (22, 0.018182517396542728), (23, 0.01654867842105231), (24, 0.0023326896204080047), (25, 0.009397233112264506), (26, 0.0029393760459229144), (27, 0.002689925036944037), (28, 0.012972820686400842), (29, 0.04078294057792885), (30, 0.012658123583836433), (31, 1.0), (32, 0.026064451022668703), (33, 0.009902740061187342), (34, 0.003050130652140327), (35, 0.002828198227520585), (36, 0.052237654246821696), (37, 0.

In [92]:
len(similarity_score)

96

In [93]:
# sorting the movies based on their similarity score

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 
print(sorted_similar_movies)

[(31, 1.0), (13, 0.16125614660092263), (15, 0.14449469925198977), (94, 0.08539489728162121), (4, 0.08448870404946178), (77, 0.08433285529400818), (12, 0.0787342824025054), (14, 0.07432401233409537), (17, 0.0723431156734935), (3, 0.07227296785546955), (6, 0.07012483412518958), (62, 0.06977987015792655), (1, 0.06663144744190379), (79, 0.06269766711218261), (45, 0.0612755659366493), (47, 0.05621066072725312), (40, 0.05573928143556555), (48, 0.05551365375880685), (80, 0.054637159494677345), (36, 0.052237654246821696), (18, 0.04917194123364781), (2, 0.04906565588283801), (68, 0.04877629734923402), (82, 0.04528297857515809), (59, 0.044534705959150524), (37, 0.04380180755573995), (9, 0.04283488994811792), (41, 0.042544323197962836), (29, 0.04078294057792885), (67, 0.036508402900583645), (83, 0.03406669803338319), (65, 0.033112711001367465), (91, 0.031908611651137155), (8, 0.03069166073852641), (89, 0.029818383097638197), (84, 0.028722317990109027), (7, 0.027295469470052014), (16, 0.0262992342

In [94]:
# print the name of similar movies based on the index

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

Movies suggested for you : 

1 . Alice in Wonderland
2 . The Lone Ranger
3 . The Chronicles of Narnia: Prince Caspian
4 . Interstellar
5 . John Carter
6 . The Jungle Book
7 . Pirates of the Caribbean: Dead Man's Chest
8 . Man of Steel
9 . Pirates of the Caribbean: On Stranger Tides
10 . The Dark Knight Rises
11 . Tangled
12 . The Chronicles of Narnia: The Lion, the Witch and the Wardrobe
13 . Pirates of the Caribbean: At World's End
14 . Snow White and the Huntsman
15 . X-Men: Days of Future Past
16 . Jack the Giant Slayer
17 . Green Lantern
18 . The Great Gatsby
19 . Maleficent
20 . Oz: The Great and Powerful
21 . Men in Black 3
22 . Spectre
23 . Hugo
24 . The Lovers
25 . A Christmas Carol
26 . The Amazing Spider-Man 2
27 . Batman v Superman: Dawn of Justice
28 . Toy Story 3
29 . Spider-Man 2


In [95]:
movie_name = input(' Enter your favourite movie name : ')

list_of_all_titles = movies_data['title'].tolist()

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

close_match = find_close_match[0]

index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]

similarity_score = list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

 Enter your favourite movie name : Iron Man
Movies suggested for you : 

1 . Hugo
2 . King Kong
3 . The Jungle Book
4 . Spider-Man 3
5 . Indiana Jones and the Kingdom of the Crystal Skull
6 . Pirates of the Caribbean: At World's End
7 . WALL·E
8 . Spider-Man 2
9 . Men in Black 3
10 . Toy Story 3
11 . Inception
12 . The Hobbit: The Battle of the Five Armies
13 . Prince of Persia: The Sands of Time
14 . The Hobbit: The Desolation of Smaug
15 . Green Lantern
16 . X-Men: Days of Future Past
17 . Man of Steel
18 . Alice in Wonderland
19 . The Mummy: Tomb of the Dragon Emperor
20 . The Great Gatsby
21 . The Chronicles of Narnia: Prince Caspian
22 . Big Hero 6
23 . Harry Potter and the Half-Blood Prince
24 . How to Train Your Dragon
25 . Jupiter Ascending
26 . Wreck-It Ralph
27 . Transformers: Dark of the Moon
28 . The Golden Compass
29 . Batman v Superman: Dawn of Justice
